## Problem 1

In [2]:
import numpy as np

def test_nonZero(arr):
    return np.all(arr != 0)

#example
a = np.array([1,2,3])
b = np.array([0,1,2])
c = np.array([1,0,2])

#test
print(test_nonZero(a))
print(test_nonZero(b))
print(test_nonZero(c))

True
False
False


## Problem 2

In [3]:
import numpy as np

def test_array_any_nonzero(arr):
    return np.any(arr != 0)

# example usage
a = np.array([1, 2, 3])
b = np.array([0, 4, 5])
c = np.array([6, 7, 8, 0])

print(test_array_any_nonzero(a))  
print(test_array_any_nonzero(b))
print(test_array_any_nonzero(c)) 

True
True
True


## Problem 3

In [4]:
import numpy as np

def test_array_equality(arr1, arr2, tol=1e-9):
    exact_equality = np.array_equal(arr1, arr2)
    within_tolerance = np.allclose(arr1, arr2, atol=tol)
    return exact_equality, within_tolerance

# example usage
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 3.000000001])
d = np.array([1, 2, 4])

# exact equality
print(test_array_equality(a, b))  
print(test_array_equality(a, c))  
print(test_array_equality(a, d))  

# equality within a tolerance of 1e-8
print(test_array_equality(a, c, tol=1e-8))  

(True, True)
(False, True)
(False, False)
(False, True)


## Problem 4

In [5]:
import numpy as np

zeros = np.zeros(10)
ones = np.ones(10)
fives = np.full(10, 5)

result = np.concatenate((zeros, ones, fives))

print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


## Problem 5

In [6]:
import numpy as np

arr = np.arange(30, 71)

print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## Problem 6

In [7]:
import numpy as np

identity = np.identity(3)

print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Problem 7

In [8]:
import numpy as np

random_number = np.random.rand()

print(random_number)

0.29341053573190923


## Problem 8

In [9]:
import numpy as np

random_array = np.random.randn(15)

print(random_array)

[-0.54955564 -0.74633217 -0.53925054  0.37329929  0.7579668   0.22863161
 -0.75021731 -1.77221294 -2.30958753 -0.4419649   1.57327048  0.77503441
 -0.97382958  0.08878785  0.05763129]


## Problem 9

In [10]:
import numpy as np

vector = np.arange(15, 56)

print("Original vector:", vector)

# Slice the vector to exclude first and last elements
new_vector = vector[1:-1]

print("Modified vector:", new_vector)

Original vector: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
Modified vector: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


## Problem 10

In [11]:
import numpy as np

vector = np.random.randint(0, 11, size=5)

print(vector)

[1 2 8 2 7]


## Problem 11

In [12]:
import numpy as np

matrix = np.ones((10, 10))
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Problem 12

In [13]:
import numpy as np

matrix = np.zeros((5, 5))
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## Problem 13

In [14]:
import numpy as np

matrix = np.zeros((4, 4))
matrix[::2, 1::2] = 1
matrix[1::2, ::2] = 1

print(matrix)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


## Problem 14

In [15]:
import numpy as np

# Define two arrays to be saved
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Save the arrays in a compressed file
np.savez_compressed('my_arrays.npz', arr1=array1, arr2=array2)

# Load the arrays from the file
loaded_data = np.load('my_arrays.npz')

# Retrieve the arrays from the loaded data
loaded_array1 = loaded_data['arr1']
loaded_array2 = loaded_data['arr2']

# Print the loaded arrays
print("Loaded array 1:")
print(loaded_array1)
print("Loaded array 2:")
print(loaded_array2)

Loaded array 1:
[1 2 3]
Loaded array 2:
[4 5 6]


## Problem 15

In [16]:
import numpy as np

# Create an array of 40 pseudo-randomly generated values
arr = np.random.rand(40)

# Select values greater than 0.5
selected_values = arr[arr > 0.5]

# Print the original array and the selected values
print("Original array:")
print(arr)
print("Selected values:")
print(selected_values)

Original array:
[0.61864369 0.62924159 0.88511625 0.90602614 0.79866621 0.22025145
 0.51418641 0.46200938 0.79739074 0.99545556 0.09728076 0.42436123
 0.33658714 0.14814736 0.40898526 0.39892523 0.71068054 0.62837212
 0.68917696 0.4705348  0.78203856 0.46560408 0.98228615 0.62554312
 0.4736051  0.11532385 0.12864725 0.98376999 0.43102489 0.77990202
 0.13403764 0.17859613 0.67686064 0.30494615 0.2143357  0.78434247
 0.68954034 0.93623652 0.15072557 0.84050005]
Selected values:
[0.61864369 0.62924159 0.88511625 0.90602614 0.79866621 0.51418641
 0.79739074 0.99545556 0.71068054 0.62837212 0.68917696 0.78203856
 0.98228615 0.62554312 0.98376999 0.77990202 0.67686064 0.78434247
 0.68954034 0.93623652 0.84050005]


## Problem 16

In [17]:
import numpy as np

# Given array
arr = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])

# Specified number
num = 5

# Extract numbers less and greater than the specified number
less_than_num = arr[arr < num]
greater_than_num = arr[arr > num]

# Print the results
print("Numbers less than", num, ":", less_than_num)
print("Numbers greater than", num, ":", greater_than_num)

Numbers less than 5 : [1 3 2 4]
Numbers greater than 5 : [7 9 6 8]
